# Generated by Django 2.2.6 on 2019-10-13 18:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(unique=True, upload_to=tiles.models.image_upload_to)),
                ('connections', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rotation', models.PositiveSmallIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='tiles.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('tiles', models.ManyToManyField(related_name='compositions', to='tiles.Tile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tile',
            constraint=models.UniqueConstraint(fields=('image', 'rotation'), name='unique_image_and_rotation'),
        ),
    ]
