# Generated by Django 2.2.6 on 2019-10-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('tiles', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='public',
            field=models.BooleanField(default=False),
        )
    ]
