# Generated by Django 3.1 on 2020-08-14 11:25

from django.db import migrations, models


def rename_public_to_featured(apps, schema_editor):
    Person = apps.get_model('tessellation', 'Composition')
    for person in Person.objects.filter(public=True, featured=False):
        person.featured = True
        person.save()
    for person in Person.objects.filter(public=False):
        person.public = True
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tessellation', '0004_composition_public_requested_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='public_requested_at',
            new_name='featured_requested_at',
        ),
        migrations.AddField(
            model_name='composition',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(rename_public_to_featured),
    ]
