# Generated by Django 3.1 on 2020-10-10 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tessellation', '0005_composition_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='self_connect',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BooleanField(), null=True, size=None
            ),
        ),
    ]
