# Generated by Django 3.1 on 2020-10-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tessellation', '0006_image_self_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='self_connect',
        ),
    ]
