# Generated by Django 3.1 on 2020-10-30 21:09

from django.db import migrations, models

import tessellation.models


class Migration(migrations.Migration):

    dependencies = [
        ('tessellation', '0007_remove_image_self_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='image',
            field=models.FileField(
                null=True,
                unique=True,
                upload_to=tessellation.models.composition_upload_to,
            ),
        ),
    ]
