# Generated by Django 3.1.3 on 2020-11-08 22:40

from django.db import migrations, models
import tessellation.models


class Migration(migrations.Migration):

    dependencies = [
        ('tessellation', '0010_composition_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='image',
            field=models.FileField(null=True, upload_to=tessellation.models.composition_upload_to),
        ),
    ]
